### ISSUE TITLE
🎉 Feature requests

### ISSUE THREAD

**Issue by antonplagemann** [piuswalter/BigBlueButton-Control-Panel#1]
Nice work! 🥇  
I have the following feature requests (sorted by priority) 🙂 

- New sorting of emojis for ease of access. From left to right: `happy, neutral, confused, sad, away, applause, thumbsUp, thumbsDown, raiseHand`
- Shortcut for turning presentator webcam on/off
- Basic emojis for direct usage in chat (z.B. 🙂😐😕🙁👏👍👎✋🍺)
- Quick answers for the global chat (e.g. `Sie sind noch stumm geschaltet 😊`, `Ihr Mikrofon ist noch an 😊`)
- Emoji and hands escalation as in BBCCP

**Comment by tjarbo** [comment]
To interact with the chat:
```js
// Prepare
const triggerReact = new Event('input', { bubbles: true});
const bbbInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype, "value").set;
const bbbChatInput = document.getElementById('xxx');
const bbbChatButton = document.getElementById('xxx');

// Interact with chat
bbbInputValueSetter.call(bbbChatInput, 'this is a chat message');
bbbChatInput.dispatchEvent(triggerReact);
bbbChatButton.click();
```

Based on:
* facebook/react#19846
* https://stackoverflow.com/a/46012210

@Pius where is my :beer: ?

**Comment by piuswalter** [comment]
Hello @antonplagemann,
every possible feature of your request is implemented now. Unfortunately there is no possibility to implement the escalation stuff like in BCCP caused the limitation of BigBlueButton in relation to fastly change the current status of a user.

**Comment by antonplagemann** [comment]
Nice! Thanks for your dedication and support! 🎖️ 💯 💪 🥇 🏆 🎉 🥳 💥
